### ISSUE TITLE
Eu, como conselheiro, desejo criar uma reunião para que outros conselheiros possam saber quando haverá uma reunião do conselho.

### ISSUE THREAD

**Issue by Thiagotrfm** [fga-gpp-mds/2017.2-AjudaConselheiro-Frontend#107]
- [x] A pesquisa de escola deverá ser feita pela US abaixo.
- [x] O campo de data deverá ser um “Date Picker” com as futuras datas possíveis.
- [x] Os campos de horário, deverão mostrar os horários em intervalos de 30 minutos.
   - Exemplo: 17:30, 18:00, 18:30…
- [x] O botão “Agendar” só estará disponível se todos os campos estiverem preenchidos corretamente.
- [x] Deverão ser notificados:
   - Sucesso ao enviar para a API.
   - Falha ao enviar para a API.
   - Campo inválido.

**Comment by filypsdias** [comment]
Fora implementado a função newScheduling que posta na nuvem os detalhes de uma reunião. O código de postagem para um agendamento é o 137.
