### ISSUE TITLE
TS#110 - Associação de novos tipos de perfis ao usuário

### ISSUE THREAD

**Issue by matheusoliveira30** [fga-gpp-mds/2017.2-AjudaConselheiro-Frontend#110]
Como discutido na sprint passada, seria mais adequado criar novos tipos de perfis para o aplicativo na nuvem cívica, tais como:
- Conselheiro
- Presidente de conselho
- Admin
- Em autorização

Esses iriam possibilitar a implementação de mais funcionalidades de forma eficiente no aplicativo.

Além disso, é necessário associar o usuário recém-cadastrado com o tipo de perfil "Em autorização", o que ainda não é feito pelo aplicativo.

**Comment by IolaneAndrade** [comment]
- Criamos os novos tipos de perfil;
- Começamos a atualizar o método Http; 
- Falta a associação  com o usuário;
- Falta teste;

**Comment by IolaneAndrade** [comment]
- A associação do perfil com o usuário foi realizada;
- A maior parte dos testes de user.service foram concluídos; 
- Testes de profile.service foram iniciados.
