### ISSUE TITLE
TS#116 Utilizar a API do IBGE para a seleção de estado e município na criação de conselho.

### ISSUE THREAD

**Issue by gabrielziegler3** [fga-gpp-mds/2017.2-AjudaConselheiro-Frontend#116]

**Comment by gabrielziegler3** [comment]
Foi feita uma reestruturação da API do IBGE em um componente único para possibilitar o reuso de código.
```
app
└─ibge
│   ibge.component.css
│   ibge.component.html
│   ibge.component.spec.ts
│   ibge.component.ts
```
Sendo importados no módulo de `council-group`

**Comment by pAmanda** [comment]
Implementamos o cadastro e a busca de conselho usando a api do IBGE com sucesso. Agora estamos começando a fazer o teste das componentes e por último faremos uma refatoração no design.
