### ISSUE TITLE
Eu, como conselheiro, desejo solicitar a participação em um conselho para que eu possa realizar minhas atividades de conselho.

### ISSUE THREAD

**Issue by joao4018** [fga-gpp-mds/2017.2-AjudaConselheiro-Frontend#141]
Critérios de Aceitação:

- [x] Somente deverá ser permitido a solicitação de participar de um conselho caso o usuário esteja autenticado e logado no site.

- [x] Página de pesquisa de conselho deverá apresentar o botão “Participar”. 

- [x] Enviar solicitação para a participação para o presidente do conselho.

- [x] Enviar por email as solicitações dos conselheiros para o presidente.

- [x] Todas as funções criadas deverão ser testadas com no mínimo 90% de cobertura.

**Comment by pAmanda** [comment]
Todas as funcionalidades foram implementadas com sucesso. A funcionalidade de enviar e-mail não é necessária já que enviar notificação já funciona. Foi uma decisão do grupo na última reunião
