### ISSUE TITLE
Ambiente Homologação

### ISSUE THREAD

**Issue by RochaCarla** [fga-gpp-mds/2017.2-AjudaConselheiro-Frontend#144]
Disponibilizar o ambiente de homologação

**Comment by IolaneAndrade** [comment]
@RochaCarla  o ambiente já está disponível em:
https://ajudaconselheiro-mdsgpp-22017.firebaseapp.com/

**Comment by matheusoliveira30** [comment]
Estão sendo feitas algumas otimizações no Travis e um possível deploy automatizado. Logo após, a issue pode ser fechada.

EDIT: O deploy não está conseguindo fazer as solicitações HTTP necessárias. Estamos trabalhando nisso! =)

**Comment by matheusoliveira30** [comment]
**Atualizando sobre o deploy:**
- Achávamos que o problema estava principalmente na forma que o deploy estava sendo configurado no Firebase, que estava bloqueando as solicitações HTTP. Então, considerados o deploy como incompleto e buscamos alternativas como o Heroku e o Google Cloud.
- Após feito deploy no Heroku, o mesmo problema apareceu. Aprofundando no problema, vimos que a solução mais rápida é permitir que o navegador web utilizado não bloqueie solicitações "Mixed Content". Ao realizar essa alteração, o deploy se comportou como esperado.
- _Link do deploy no Firebase:_ https://ajudaconselheiro-mdsgpp-22017.firebaseapp.com/
- _Link do deploy no Heroku_: https://ajuda-conselheiro-mdsgpp-22017.herokuapp.com

**Sobre o problema:**
- A principal API do projeto, a Nuvem Cívica, ainda não tem suporte à solicitações HTTPS, como já foi esclarecido em reuniões com os responsáveis pela API. Logo, todas as solicitações são feitas via HTTP.
- Ao disponibilizar o deploy nos serviços testados, todos eles disponibilizam o sistema via HTTPS.
- Quando o sistema no deploy necessitava fazer uma solicitação da API, via HTTP, o navegador web bloqueava a solicitação, alegando "Mixed Content".
- Esse erro ocorre quando um site utilizando HTTPS tenta fazer uma requisição não segura, usando HTTP.
- O problema poderia ser contornado ao utilizar um servidor que faça a mediação das solicitações da API. O frontend desenvolvido iria fazer apenas solicitações HTTPS para esse novo servidor e o servidor iria buscar nos endpoints da API os dados solicitados e retorná-los para o front.
- _Breve descrição de como configurar o navegador:_ https://www.bu.edu/tech/support/browsers/display-mixed-content/
