### ISSUE TITLE
Eu, como conselheiro, desejo efetuar login no AjudaConselheiro para que eu possa usufruir das ferramentas que o sistema proporciona.

### ISSUE THREAD

**Issue by Thiagotrfm** [fga-gpp-mds/2017.2-AjudaConselheiro-Frontend#40]
Critérios de aceitação:

- [x] O _login_ deve campos para a inserção do e-mail e senha do usuário.

- [ ] O campo de e-mail só poderá aceitar endereços de e-mail válidos.

- [x] O _login_ só poderá ser efetuado se os campos estiverem preenchidos.

- [ ] O _login_ poderá ser iniciado ao pressionar "ENTER" ou ao clicar no botão "Acessar".

- [x] Caso as informações presentes nos campos não possam relação com a base de usuários (_Login_ inválido), deverá ser apresentado um alerta ou pop-up indicando falha de autenticação.

- [x] O _login_ só poderá ser efetuado caso a base de dados (API Nuvem Cívica) retorne com sucesso um _token_ de _login_.

- [x] Deverá existir um botão "Esqueci minha senha".

**Comment by MFire30** [comment]
US criteria were not met for Sprint 1. Going back to Product Backlog.
