### ISSUE TITLE
TS#41 Eu, como conselheiro, desejo realizar a edição dos meus dados de cadastro no AjudaConselheiro para que estes estejam sempre atualizados e corretos.

### ISSUE THREAD

**Issue by Thiagotrfm** [fga-gpp-mds/2017.2-AjudaConselheiro-Frontend#41]
Critérios de aceitação:

- São obrigatórios os campos de:
- [x] Nome completo
- [ ] CPF
- [ ] Telefone
- [ ] Segmento
- [ ] Email
- [x] Senha
- Espera-se que os seguintes campos estejam validados:
- [ ] CPF (XXX.XXX.XXX-XX)
- [ ] Telefone ()
- [ ] Email(_@_._)
- Também é desejado que possua:
- [ ] Testes unitários

**Comment by filypsdias** [comment]
Na situação atual, torna-se impossível editar campos de CPF, Telefone, Segmento, Email e Senha. A [API](https://github.com/AppCivicoPlataforma/AppCivico/blob/master/MetamodeloAPI.md) não possui um método PUT para tais campos. 
O método 'PUT /rest/pessoas/{codPessoa}' retorna:

`
{
  "CEP": "string",
  "biografia": "string",
  "dataNascimento": "2017-11-05T12:15:13.462Z",
  "latitude": 0,
  "links": [
    {
      "href": "string",
      "rel": "string",
      "templated": true
    }
  ],
  "longitude": 0,
  "nomeCompleto": "string",
  "nomeUsuario": "string",
  "sexo": "string"
}
`
