### ISSUE TITLE
Eu, como conselheiro, desejo deletar minha conta para que o meu vínculo com o sistema seja desfeito.

### ISSUE THREAD

**Issue by Thiagotrfm** [fga-gpp-mds/2017.2-AjudaConselheiro-Frontend#43]
- [x] A funcionalidade de deletar conta deverá ser acessada por um botão "Deletar Conta", na página de Perfil. Esse botão deverá ser da cor vermelha e possuir um ícone de "X" no lado esquerdo.

- [ ] Ao clicar no botão, deverá aparecer um Modal explicando que a conta será deletada se o usuário continuar. Então, deverão existir dois botões: "Continuar" e "Cancelar".

- [ ]  Ao selecionar "Continuar", o Modal é atualizado para que o usuário preencha a senha dele. Nessa nova página, deverão existir dois botões: "Deletar conta" e "Cancelar".

- [x] "Deletar Conta" irá verificar na Nuvem Cívica se a senha está válida e então irá permitir a remoção da conta. O botão só estará disponível caso o campo de senha esteja preenchido corretamente (Tamanho mínimo).

- [x] Ao realizar a remoção da conta, deverá ser removido apenas o perfil de aplicativo do usuário. Assim, o usuário não poderá mais fazer login na aplicação, mas sua conta ainda existe na nuvem para caso ele utilize outro aplicativo.

- [x] Testes unitários das funcionalidades descritas acima e novas funções de ProfileService.

**Comment by IolaneAndrade** [comment]
- A funcionalidade de deletar conta foi realizada;
- Um botão "Deletar Conta", na página de Perfil da cor vermelha com um X do lado esquerdo foi inserido;
