### ISSUE TITLE
Eu, como conselheiro, desejo criar uma conta no AjudaConselheiro para que eu possa ter acesso às ferramentas que o sistema me oferece.

### ISSUE THREAD

**Issue by Thiagotrfm** [fga-gpp-mds/2017.2-AjudaConselheiro-Frontend#46]
Critérios de aceitação: 

- [x] Deverão existir os campos: E-mail, CPF, Senha, Confirmar Senha.

- [x] O campo "E-mail" só poderá aceitar endereços de e-mail válidos.

- [ ] O campo "CPF" só poderá aceitar números de CPF que estão adequados à lógica de validação de CPF.

- [x] O campo "Senha" só poderá aceitar senhas de no mínimo seis caracteres e no máximo vinte.

- [x] O cadastro só poderá ser efetuado caso todos os campos estejam preenchidos corretamente.

- [ ] As possíveis falhas de cadastro com a API (400 até 404) deverão ser informadas por meio de alerta ou pop-up.

**Comment by matheusoliveira30** [comment]
US criteria were not met for Sprint 1. Going back to Product Backlog.

**Comment by stebezs** [comment]
The acceptance criteria have not been met. Back to the backlog.
