### ISSUE TITLE
Eu, como presidente de um conselho, desejo criar um conselho para que meus conselheiros possam ser cadastrados.

### ISSUE THREAD

**Issue by Thiagotrfm** [fga-gpp-mds/2017.2-AjudaConselheiro-Frontend#47]
Critérios de aceitação:

- [x] Na base de dados da API Nuvem Cìvica, deverá existir um "Super Grupo" chamado "Conselhos".

- [x] Deverão existir os campos: Município, UF, Descrição.

- [x] Deverá existir um botão "Cadastrar conselho" para efetuar o cadastro.

- [x] Só será possível cadastrar o conselho caso os campos estiverem devidamente preenchidos.

- [x] Só será possível cadastrar o conselho caso não exista nenhum outro para o mesmo município e UF.

- [x] Os possíveis erros que a API pode retornar (401 até 404) deverão ser informados via alerta ou pop-up.

**Comment by matheusoliveira30** [comment]
US criteria were not met for Sprint 1. Going back to Product Backlog.
