### ISSUE TITLE
Eu, como conselheiro, desejo poder pesquisar um conselho para que eu possa me cadastrar no conselho ao qual pertenço.

### ISSUE THREAD

**Issue by IolaneAndrade** [fga-gpp-mds/2017.2-AjudaConselheiro-Frontend#59]
Critérios de aceitação:

- [x] O Conselho pode ser pesquisado utilizando: CAE, UF, Município.

- [x] O Conselho compatível com os critérios de pesquisa deverá aparecer em um menu estilo dropdown.

- [x] Ao selecionar o Conselho pesquisado, deverão ser apresentadas informações sobre ela abaixo do menu dropdown. Essas informações são: CAE, UF, Município.

- [x] Erros de comunicação com a base de dados do Conselho (Código 400 ou falha na conexão) deverão ser informados por meio de um alerta ou pop-up.

- [x] CAE-UF-MUNICIPIO

**Comment by stebezs** [comment]
The acceptance criteria have not been met. Back to the backlog.
