### ISSUE TITLE
TS#73 Testes que cubram as respostas nas comunicações dos serviços de criar um conselho

### ISSUE THREAD

**Issue by gabrielziegler3** [fga-gpp-mds/2017.2-AjudaConselheiro-Frontend#73]
As possíveis respostas são: 201, 400, 401, 404.

**Comment by matheusoliveira30** [comment]
A "council-group.service.ts" foi testada com cobertura 100% e alguns métodos foram refatorados e otimizados, mantendo suas funcionalidades.
Ainda é necessário testar a "create-council-group.component.ts".

**Comment by pAmanda** [comment]
A "create-council-group.component.ts" está com 93.34% de cobertura de teste e seus métodos foram refatorados para melhorar a manutenibilidade.
