### ISSUE TITLE
[Bug] Criação de usuário em aplicativo errado

### ISSUE THREAD

**Issue by filypsdias** [fga-gpp-mds/2017.2-AjudaConselheiro-Frontend#81]
Quando é criado um novo usuário, ele é salvo em 'http://mobile-aceite.tcu.gov.br:80/appCivicoRS/rest/pessoas' ao invés de ser salvo em 'http://mobile-aceite.tcu.gov.br:80/appCivicoRS/rest/pessoas/?codAplicativo=462'. 

Para reproduzi-lo basta criar um usuário e chegar o link 'http://mobile-aceite.tcu.gov.br:80/appCivicoRS/rest/pessoas/?codAplicativo=462'. 

Para resolver, recomenda-se trocar a url atual.

**Comment by matheusoliveira30** [comment]
Não é possível cadastrar um novo usuário diretamente no aplicativo.

Primeiramente, é necessário criar um "tipo de perfil" para o aplicativo e então associar esse tipo criado ao usuário desejado. A partir desse ponto, o usuário possui relação com o aplicativo desejado.

A criação de tipos de perfil está sendo feita, atualmente, na issue #92.
