### ISSUE TITLE
[Bug] Autenticação do usuário

### ISSUE THREAD

**Issue by Thiagotrfm** [fga-gpp-mds/2017.2-AjudaConselheiro-Frontend#82]
Quando o login é realizado, apenas o token do usuário é salvo na aplicação, deixando de salvar dados essenciais do usuário. No corpo da resposta de autenticação estão inseridos os dados como abaixo:

{
  "nomeUsuario": "Teste23",
  "cod": 4317,
  "email": "teste23@tcu.gov.br",
  "emailVerificado": false,
  "links": [
    {
      "rel": "self",
      "href": "http:\/\/mobile-aceite.tcu.gov.br\/appCivicoRS\/rest\/pessoas\/4317"
    }
  ]
}

E o header:

Date: Thu, 18 May 2017 18:08:27 GMT
Server: Apache-Coyote/1.1
Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Headers: email, senha, senhaAtual, novaSenha, credencial
Access-Control-Allow-Headers: appToken, appIdentifier, facebookToken, googleToke
Access-Control-Expose-Headers: appToken, Location
Access-Control-Allow-Methods: GET, POST, PUT, DELETE
Access-Control-Allow-Origin: *
appToken: v1_6E8EACCC6B06AC2D08829E2B6917397FC24E0C4CD33E01CC2B90DE16F25EF98288F43E80FADF857C52EDE57AE7633A1A8356D36DD88F89C2AF0D9D846C1F843B099FACA8C6E398DD6B49F28AA4EC8BF80258CB5C2B02AA45B4B07043091B365D9D33747C06C14B7C50FCEE0DAA573D
Content-Type: application/json;charset=UTF-8

Reprodução: Ao fazer o login, apenas o tokenApp é salvo no localStorage.
Problema: Precisamos dos dados do usuário.

**Comment by MFire30** [comment]
Anotado.

**Comment by matheusoliveira30** [comment]
Corrigi na branch TS#82.

Agora, basta você importar a UserService e utilizar o método getLoggedUser(). Esse método recebe nenhum parâmetro e retorna um objeto JS formatado, com os dados do usuário.

Aproveitei e corrigi também um erro que tinha que o login estava sendo feito mesmo ao utilizar um email inválido. Foi feita uma alteração na lógica dos IFs e regex e agora a solicitação não é feita para a API.

**Comment by pAmanda** [comment]
Arrumamos um erro que quando o usuário fazia logout, os dados do usuário ainda ficavam setados no local storage e a variável isLoggedIn sempre ficava false. Agora, os dados são setador e removidos corretamente.

**Comment by matheusoliveira30** [comment]
Versões iniciais dos testes dos métodos corrigidos e refatorados foram colocadas na branch TS#42. Amanhã, os testes finais serão feitos e então solicitado um novo PR para fechar a issue.

**Comment by matheusoliveira30** [comment]
Os testes foram finalizados e a branch TS#82 está pronta para ser aceita no pull request.
