### ISSUE TITLE
Eu, como conselheiro, desejo criar um perfil para adicionar informações extras sobre mim.

### ISSUE THREAD

**Issue by Thiagotrfm** [fga-gpp-mds/2017.2-AjudaConselheiro-Frontend#92]
- [ ] O campo de email verificado será utilizado para saber se o usuário já tem um perfil.
- [x] Enquanto o usuário não tiver perfil, nada será mostrado dentro da aplicação, apenas as barras de navegação e rodapé. No corpo da página será mostrado uma cotificação com um link para adicionar o CPF.
- [x] Haverá uma página onde o usuário irá inserir o CPF, onde o mesmo deverá ser validado.
- [ ] Após clicar em salvar, será apresentado uma confirmação do CPF inserido.
- [x] O campo de ehPresidente será inserido como _false_ por _default_
- [x] Com a confirmação, o perfil será postado na nuvem cívica e linkado com o usuário atual.
- [ ] O campo de email verificado será mudado para _true_

**Comment by joao4018** [comment]
O campo de e-mail verificado será utilizado para saber se o usuário já tem um perfil.
O campo de email verificado será mudado para true.
Não encontrei relação entre e-mail verificado e perfil (o que tem a ver um com o outro).
Como verificar um e-mail através de um perfil?
Lembrando que o e-mail não ta sendo verificado de fato, isso deve ser feito por um e-mail para o usuário verificar, acho um grande retrabalho depois de fazer isso tudo que não será usado

 O campo de ehPresidente será inserido como false por default
Solução pensada, criar um tipo de perfil para conselheiro e um para presidente, e assim nao haverá necessidade do uso do campo ehPresidente.

**Comment by joao4018** [comment]
Notei que o campo emailVerificado não existe um método PUT pra atualizar esse campo, ele é alterado no momento que é criado, é como uma verificação prévia, você só pode entrar caso confirme seu e-mail que ai terá o cadastro finalizado, sugiro uma leitura na [API](https://github.com/AppCivicoPlataforma/AppCivico/blob/master/MetamodeloAPI.md#cadastrar-perfil) da nuvem cívica, pra ter uma noção do que acontece com o atributo e sugiro mais, uma estória somente para o uso do atributo emailVerificado.
